# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175E2wqxu8JzujBRTkBhHUyKf5mTb-eik

<div align="center">

#### Lab 3

# National Tsing Hua University

#### Spring 2025

#### 11320IEEM 513600

#### Deep Learning and Industrial Applications
    
## Lab 3: Anomaly Detection in Industrial Applications

</div>

### Introduction

In today's industrial landscape, the ability to detect anomalies in manufacturing processes and products is critical for maintaining quality, efficiency, and safety. This lab focuses on leveraging deep learning techniques for anomaly detection in various industrial applications, using the MVTEC Anomaly Detection Dataset. By employing ImageNet-pretrained models available in torchvision, students will gain hands-on experience in classfying defects and irregularities across different types of industrial products.

Throughout this lab, you'll be involved in the following key activities:
- Explore and process the MVTec Anomaly Detection Dataset.
- Apply ImageNet-pretrained models from [Torchvision](https://pytorch.org/vision/stable/models.html) to detect anomalies in industrial products.
- Evaluate the performance of the models to understand their effectiveness in real-world industrial applications.

### Objectives

- Understand the principles of anomaly detection in the context of industrial applications.
- Learn how to implement and utilize ImageNet-pretrained models for detecting anomalies.
- Analyze and interpret the results of the anomaly detection models to assess their practicality in industrial settings.

### Dataset

The MVTec AD Dataset is a comprehensive collection of high-resolution images across different categories of industrial products, such as bottles, cables, and metal nuts, each with various types of defects. This dataset is pivotal for developing and benchmarking anomaly detection algorithms. You can download our lab's dataset [here](https://drive.google.com/file/d/19600hUOpx0hl78TdpdH0oyy-gGTk_F_o/view?usp=share_link). You can drop downloaded data and drop to colab, or you can put into yor google drive.

### References
- [MVTec AD Dataset](https://www.kaggle.com/datasets/ipythonx/mvtec-ad/data) for the dataset used in this lab.
- [Torchvision Models](https://pytorch.org/vision/stable/models.html) for accessing ImageNet-pretrained models to be used in anomaly detection tasks.
- [State-of-the-Art Anomaly Detection on MVTec AD](https://paperswithcode.com/sota/anomaly-detection-on-mvtec-ad) for insights into the latest benchmarks and methodologies in anomaly detection applied to the MVTec AD dataset.
- [CVPR 2019: MVTec AD — A Comprehensive Real-World Dataset for Unsupervised Anomaly Detection] for the original paper of MVTec AD dataset.
"""

import glob
import matplotlib.pyplot as plt
import random
from tqdm.auto import tqdm
import cv2
import numpy as np

from google.colab import drive

drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/PhD/113 DLIA/HW3')
print(os.listdir('.'))

import os

print("目前目錄：", os.getcwd())  # 確認你切到正確的目錄
print("HW3 目錄下的內容：", os.listdir('.'))  # 看看是否有 cable 資料夾
print("cable 資料夾內容：", os.listdir('cable'))  # 看子資料夾

import os

defect_classes = sorted([d for d in os.listdir('cable/test')])
print(f"📌 缺陷類別數量: {len(defect_classes)}")
print(f"📌 缺陷類別名稱: {defect_classes}")
import glob

train_imgs = glob.glob('cable/train/good/*.png')
test_imgs = glob.glob('cable/test/*/*.png')  # 包含 good 和 defects

print(f"📌 訓練圖片數量: {len(train_imgs)}")
print(f"📌 測試圖片數量: {len(test_imgs)}")
print(f"📌 圖片總數: {len(train_imgs) + len(test_imgs)}")
from collections import defaultdict

# 統計測試集中每類的圖片數量
test_dist = defaultdict(int)
for path in test_imgs:
    cls = path.split('/')[-2]
    test_dist[cls] += 1

print("📌 測試集分佈：")
for k, v in test_dist.items():
    print(f" - {k}: {v} 張")

print(f"📌 訓練集只有 'good': {len(train_imgs)} 張")
import cv2

sample_img = cv2.imread(train_imgs[0])
h, w, c = sample_img.shape
print(f"📌 圖片尺寸: {w}x{h}, channels: {c}")

file_paths = glob.glob('cable/test/*/*.png')
if not file_paths:
    print("No files found matching the pattern. Please check the file path.")
file_paths = sorted([path for path in file_paths if path.split('/')[-1] in [f'{i:03}.png' for i in range(10)]])
print(file_paths)
print(len(file_paths))

# 讀取所有圖片 → 轉成 RGB → 儲存進一個 4D NumPy 陣列
all_data = []

for img in tqdm(file_paths):
    img = cv2.imread(img)
    img = img[..., ::-1]
    all_data.append(img)

all_data = np.stack(all_data)
print(all_data.shape)

import matplotlib.pyplot as plt
import numpy as np

classes = sorted(set([path.split('/')[2] for path in file_paths]))
print(f'Classes: {classes}')
#結果：classes 是一個類別名稱的 list
images_per_class = len(all_data) // len(classes)
fig, axs = plt.subplots(len(classes), 2, figsize=(6, 4 * len(classes)),squeeze=False)

for i, class_name in enumerate(classes):
    index = i * images_per_class
    for j in range(2):
        axs[i, j].set_title(f'{i}. {class_name}')
        axs[i, j].imshow(all_data[index + j])
        axs[i, j].axis('off')

plt.tight_layout()
plt.show()

"""## A. Data Loading and Preprocessing"""

import torch
from torch.utils.data import DataLoader, TensorDataset, random_split
import numpy as np

num_classes = 9
images_per_class = 10
train_images_per_class = int(images_per_class * 0.8)
val_images_per_class = int(images_per_class * 0.2)

x_train = []
x_val = []

for i in range(num_classes):
    start_index = i * images_per_class
    x_train.extend(all_data[start_index:start_index + train_images_per_class])
    x_val.extend(all_data[start_index + train_images_per_class:start_index + images_per_class])

# The shape changes from (batch_size, height, width, channels) to (batch_size, channels, height, width)
x_train = np.transpose(np.array(x_train), (0, 3, 1, 2))
x_val = np.transpose(np.array(x_val), (0, 3, 1, 2))

y_train = np.concatenate([np.full(train_images_per_class, i) for i in range(num_classes)])
y_val = np.concatenate([np.full(val_images_per_class, i) for i in range(num_classes)])

print(f'Shape of x_train: {x_train.shape}')
print(f'Shape of x_val: {x_val.shape}')
print(f'Shape of y_train: {y_train.shape}')
print(f'Shape of y_val: {y_val.shape}')

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Dataset
from PIL import Image

resize = 256
#resize 圖片大小，影響解析度
# 可調
train_transforms = transforms.Compose(
    [
        transforms.Resize((resize, resize)),
        transforms.AutoAugment(),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
    ]
)

val_transforms = transforms.Compose(
    [
        transforms.Resize((resize, resize)),
        transforms.ToTensor(),
    ]
)

class MyDataset(Dataset):
    def __init__(self, x, y, transform=None):
        self.x = x
        self.y = torch.from_numpy(y).long()
        self.transform = transform

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        new_x = np.transpose(self.x[idx], (1, 2, 0))
        return self.transform(Image.fromarray(new_x)), self.y[idx]

batch_size = 32
# 可調 3, 32, 64
train_dataset = MyDataset(x_train, y_train, train_transforms)
val_dataset = MyDataset(x_val, y_val, val_transforms)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True, persistent_workers=True)
val_loader = DataLoader(dataset=val_dataset, batch_size=batch_size, shuffle=False, num_workers=1, pin_memory=True, persistent_workers=True)

"""## B. Defining Neural Networks"""

import torch.nn as nn
import torch.nn.functional as F
from torchvision import models
# 可調
weights='IMAGENET1K_V1' #'IMAGENET1K_V1','IMAGENET1K_V2'

model = models.resnet50(weights = weights)

# ConvNet as fixed feature extractor (freeze parameters)
for param in model.parameters():
    param.requires_grad = False

num_ftrs = model.fc.in_features
num_class = 9

# change # of class from 1000 into 8 in the last layer
model.fc = nn.Linear(num_ftrs, num_class)
print(model)

"""## C. Training the Neural Network"""

import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR, StepLR
from tqdm.auto import tqdm

train_losses = []
val_losses = []
train_accuracies = []
val_accuracies = []

#可以調
epochs = 150
learning_rate = 1e-3

model = model.cuda()

best_val_loss = float('inf')
best_val_acc = -1

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=learning_rate)
lr_scheduler = CosineAnnealingLR(optimizer, T_max=len(train_loader)*epochs, eta_min=0)

for epoch in tqdm(range(epochs)):
    # Training
    model.train()
    total_loss = 0.0
    train_correct = 0
    total_train_samples = 0

    for images, labels in train_loader:
        images = images.cuda()
        images = (images) / 255.
        labels = labels.cuda()
        optimizer.zero_grad()
        outputs = model(images)

        labels = labels.long()

        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

        train_predicted = outputs.argmax(-1)
        train_correct += (train_predicted == labels).sum().item()
        total_train_samples += labels.size(0)

    avg_train_loss = total_loss / len(train_loader)
    train_accuracy = 100. * train_correct / total_train_samples

    # Validation
    model.eval()
    total_val_loss = 0.0
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images = images.cuda()
            images = (images) / 255.
            labels = labels.cuda()
            outputs = model(images)

            labels = labels.long()

            loss = criterion(outputs, labels)
            total_val_loss += loss.item()

            predicted = outputs.argmax(-1)
            correct += (predicted == labels).sum().item()
            total += labels.size(0)

    avg_val_loss = total_val_loss / len(val_loader)
    val_accuracy = 100. * correct / total

    # Learning rate update
    lr_scheduler.step()

    # Checkpoint
    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss

    if val_accuracy > best_val_acc:
        best_val_acc = val_accuracy
        torch.save(model.state_dict(), 'model_classification.pth')

    print(f'Epoch {epoch+1}/{epochs}, Train loss: {avg_train_loss:.4f}, Train acc: {train_accuracy:.4f}%, Val loss: {avg_val_loss:.4f}, Val acc: {val_accuracy:.4f}%, Best Val loss: {best_val_loss:.4f} Best Val acc: {best_val_acc:.2f}%')

    # Store performance
    train_losses.append(avg_train_loss)
    train_accuracies.append(train_accuracy)
    val_losses.append(avg_val_loss)
    val_accuracies.append(val_accuracy)

"""### Visualizing model performance"""

import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 2, figsize=(15, 5))

# Plotting training and validation accuracy
ax[0].plot(train_accuracies)
ax[0].plot(val_accuracies)
ax[0].set_title('Model Accuracy')
ax[0].set_xlabel('Epochs')
ax[0].set_ylabel('Accuracy')
ax[0].legend(['Train', 'Val'])

# Plotting training and validation loss
ax[1].plot(train_losses)
ax[1].plot(val_losses)
ax[1].set_title('Model Loss')
ax[1].set_xlabel('Epochs')
ax[1].set_ylabel('Loss')
ax[1].legend(['Train', 'Val'])

plt.show()

"""## D. Evaluating Your Trained Model

### Load Trained Model and Evaluate
"""

# Load the trained weights
model.load_state_dict(torch.load('model_classification.pth'))

# Set the model to evaluation mode
model.eval()

test_correct = 0
test_total = 0

with torch.no_grad():
    for images, labels in val_loader:

        images = images.cuda()
        images = (images) / 255.

        labels = labels.cuda()
        labels = labels.long()

        outputs = model(images)

        predicted = outputs.argmax(-1)
        print(predicted)
        print(labels)
        test_correct += (predicted == labels).sum().item()
        test_total += labels.size(0)

print(f'Test accuracy is {100. * test_correct / test_total}%')

#把各組超參數的數據整理進一個 Python 字典，然後轉換為 pandas DataFrame，以便於展示和分析
import pandas as pd
import os

# 假設以下變量已經包含了在給定的超參數設定下從訓練過程中收集的數據
# train_losses, train_accuracies, val_losses, val_accuracies

# 最後一個 Epoch 的訓練和驗證損失及準確率
final_train_loss = train_losses[-1]
final_train_accuracy = train_accuracies[-1]
final_val_loss = val_losses[-1]
final_val_accuracy = val_accuracies[-1]

# Test accuracy
test_accuracy = 100. * test_correct / test_total

# 將所有數據組織成一個字典
result = {
    'resize': [resize],
    'epoch': [epochs],
    'learning rate': [learning_rate],


    'Train Loss': [final_train_loss],
    'Train Accuracy': [final_train_accuracy],
    'Val Loss': [final_val_loss],
    'Val Accuracy': [final_val_accuracy],
    'Test Accuracy': [test_accuracy]

}

# # 轉換字典為 pandas DataFrame
# results_df = pd.DataFrame(result)

# 轉換字典為 DataFrame 的一行
new_results_df = pd.DataFrame(result)

# CSV 文件的路徑
results_csv_file = '/content/drive/MyDrive/PhD/113 DLIA/HW3/results.csv'

# 檢查文件是否存在
if os.path.exists(results_csv_file):
    # 如果文件存在，載入現有的 DataFrame 並追加新數據
    existing_df = pd.read_csv(results_csv_file)

    updated_df = pd.concat([existing_df, new_results_df], ignore_index=True)
else:
    # 如果文件不存在，則創建一個新的 DataFrame
    updated_df = new_results_df
    existing_df = pd.DataFrame()

print(type(existing_df))
print(type(new_results_df))

# 將更新後的 DataFrame 儲存到 CSV 文件中
updated_df.to_csv(results_csv_file, index=False)
print("ok")

# 顯示更新後的 DataFrame
print(updated_df)

# 保留列名但刪除所有數據
#updated_df = updated_df[0:0]
#print(updated_df)

#updated_df.to_csv(results_csv_file, index=False)